// UI-only fixtures. No model requests, game control or real credentials; never packaged.
import http from 'node:http';
import fs from 'node:fs/promises';
const mock=`
const NAMES={jev:'Jev',local:'Laya',openai:'OpenAI'},ORIGINS={jev:'https://api.typesafe.ai/*',local:'http://127.0.0.1/*',openai:'https://api.openai.com/*'};
let settings={provider:localStorage.previewProvider||'jev',providerName:NAMES[localStorage.previewProvider||'jev'],openaiBase:'https://api.openai.com/v1',openaiKey:'',openaiModel:'',openaiMode:'tools',openaiModels:[],hasOpenaiKey:false,apiBase:'https://api.typesafe.ai/v1',model:'jev-latest',localBase:'http://127.0.0.1:8742/v1',localModel:'laya',hasLocalKey:false,apiKey:new URL(location.href).searchParams.has('nokey')?'':'sk-preview-0123456789abcdef',localKey:'',hotkey:'Alt+Shift+J',autoCamera:true,showOverlay:true,maxDecisions:2000,objective:'',allowedHosts:['laya.example.com'],hasKey:!new URL(location.href).searchParams.has('nokey'),language:localStorage.previewLanguage||'zh-CN'};
const now=Date.now();
let observation={at:now,tick:5400,gameSeconds:360,credits:8450,freeCredits:5250,army:18,harvesters:3,antiAir:4,health:.86,visibleEnemies:9,nearbyEnemies:3,power:{total:500,drain:375},threat:'pressure',rangeThreats:[{name:'SREF',range:10}],enemyMix:{vehicles:2,infantry:1,air:0},base:{x:24,y:40},ownPoints:[{x:28,y:30},{x:36,y:34},{x:38,y:30},{x:32,y:37},{x:28,y:27}],enemyPoints:[{x:44,y:24},{x:48,y:20},{x:50,y:29}],queues:[{type:'0',items:[{name:'GATECH',quantity:1,progress:.7}]},{type:'3',items:[{name:'MTNK',quantity:2,progress:.32}]}],inventory:[{kind:'E1',label:'美国大兵',count:6},{kind:'MTNK',label:'灰熊坦克',count:8},{kind:'AMCV',label:'移动基地车',count:1}]};
const history=Array.from({length:40},(_,i)=>({at:now-(39-i)*5000,gameSeconds:160+i*5,credits:10000-i*60+Math.sin(i*.6)*900,freeCredits:Math.max(0,7000-i*70+Math.sin(i*.6)*900),decisions:Math.floor(i/3),ownUnits:6+Math.floor(i/2),ownBuildings:5+Math.floor(i/8),enemyUnits:Math.max(0,Math.round(4+Math.sin(i/3)*4)),ownBuilt:Math.floor(i/2),ownLost:Math.floor(i/6),enemyDestroyed:Math.floor(i/3)}));
let status={supported:true,running:true,title:'界面预览 · 模拟对局 / UI fixture',decisions:13,credits:8450,latencyMs:287,lastTick:5400,mission:'模拟显示：派遣主力拦截基地附近的敌人',events:[{at:now,kind:'action',actionType:'produce',choice:'produce_MTNK',accepted:true,text:'生产灰熊坦克'}],observation,history,liveObservation:true,acceptedActions:31,waits:8};
if(new URL(location.href).searchParams.has('empty'))status={supported:true,running:false,title:'UI fixture · Lobby',events:[]};
const deny=new URL(location.href).searchParams.has('deny');let granted=!deny;
const overlayStatus={running:true,decisions:13,credits:8450,latencyMs:287,lastTick:5400,failures:1,losses:{ownUnits:7,ownBuildings:1,enemyUnits:23,enemyBuildings:4}};
window.chrome={tabs:{create:o=>window.open(o.url,'_blank'),query:async()=>[{id:1}]},permissions:{request:async()=>{if(deny&&!window.__grantNext)return false;granted=true;return true;}},runtime:{onMessage:{addListener(){}},sendMessage:async m=>{
 if(m.type==='PUBLIC_CONFIG')return {ok:true,value:{hotkey:settings.hotkey,language:settings.language,showOverlay:true,providerName:settings.providerName}};
 if(m.type==='OVERLAY_STATUS')return {ok:true,value:{...overlayStatus,hotkey:settings.hotkey,language:settings.language,showOverlay:true,providerName:settings.providerName}};
 if(m.type==='SET_AUTO_REPORT'){settings.autoReport=m.autoReport;return {ok:true,value:{autoReport:m.autoReport}};}
 if(m.type==='ALLOW_HOST'){settings.allowedHosts=[...new Set([...settings.allowedHosts,m.host.toLowerCase()])];return {ok:true,value:{allowedHosts:settings.allowedHosts}};}
 if(m.type==='DISALLOW_HOST'){settings.allowedHosts=settings.allowedHosts.filter(h=>h!==m.host);return {ok:true,value:{allowedHosts:settings.allowedHosts}};}
 if(m.type==='GET_SETTINGS')return {ok:true,value:{...settings,permitted:granted,origin:ORIGINS[settings.provider]}};
 if(m.type==='LIST_MODELS'){await new Promise(r=>setTimeout(r,700));if(location.search.includes('modelsfail'))return {ok:false,error:'OpenAI 拒绝了密钥（HTTP 401），请检查密钥。 Incorrect API key provided'};return {ok:true,value:{base:m.base,models:['deepseek-chat','gpt-4.1','gpt-4.1-mini','gpt-5-mini','qwen-plus']}};}
 if(m.type==='SET_LANGUAGE'){settings.language=m.language;localStorage.previewLanguage=m.language;return {ok:true,value:{language:m.language}};}
 if(m.type==='SET_OVERLAY'){settings.showOverlay=m.showOverlay;return {ok:true,value:{showOverlay:m.showOverlay}};}
 if(m.type==='TEST_CONNECTION'){await new Promise(r=>setTimeout(r,1200));if(location.search.includes('testfail'))return {ok:false,error:settings.providerName+' 连接失败，请检查地址、网络或响应格式。'};return {ok:true,value:{latencyMs:{local:9,openai:2140}[settings.provider]??123,providerName:settings.providerName,model:{local:'laya-multilingual-mlx',openai:settings.openaiModel}[settings.provider]??'jev-1.13'}};}
 if(m.type==='LOG_STATS'||m.type==='LOG_EXPORT'){const stats={entries:412,from:now-3600000,to:now,sessions:2,decisions:180,failures:3,stale:4,latency:{avg:187,max:912},providers:{local:180},models:{'laya-multilingual-mlx':180},groups:{construction:{asked:120,waits:96,avgOptions:5.2,avgConfidence:.41,waitRate:80,choices:{wait:96,produce_GAPOWR:14,produce_GAREFN:10}},vehicles:{asked:110,waits:104,avgOptions:4.1,avgConfidence:.88,waitRate:95,choices:{wait:104,produce_MTNK:6}},tactics:{asked:90,waits:20,avgOptions:4.6,avgConfidence:.93,waitRate:22,choices:{attack_enemy_base:60,wait:20,rally_front:10}}},actions:{total:320,accepted:96,skipped:14,waits:210,byType:{mission:70,produce:26},skippedReasons:{production_changed:8,queue_changed:4,unit_gone:2},acceptedProduce:{GAPOWR:14,GAREFN:8,MTNK:4}},outcomes:{},errors:1};if(m.type==='LOG_STATS')return {ok:true,value:{stats:stats,chars:512000}};return {ok:true,value:{exportedAt:new Date().toISOString(),version:'0.4.0',settings:{...settings,apiKey:undefined,localKey:undefined},stats,entries:[{at:now,kind:'decision',tick:5400,provider:'local',model:'laya-multilingual-mlx',latencyMs:181,groups:{construction:{choice:'wait',confidence:.39}}}]}};}
 if(m.type==='LOG_CLEAR')return {ok:true,value:{entries:0}};
 const matchA={id:'a',startedAt:now-5400000,endedAt:now-1800000,durationMs:3600000,gameSeconds:3300,provider:'openai',providerName:'OpenAI',providerKind:'cloud',model:'gpt-4.1-2025-04-14',configuredModel:'gpt-4.1',callMode:'tools',endpoint:'https://api.openai.com/v1/chat/completions',outputTokens:41200,totalTokens:941200,objective:'摧毁地图东北角的五角大楼',reason:'victory',outcome:'victory',decisions:412,requests:415,failures:3,acceptedActions:230,waits:512,inputTokens:900000,latencyAvg:812,credits:{start:10000,end:23450,max:31200,min:2100},armyMax:38,produced:{MTNK:22,HARV:4,GAPOWR:3,GAREFN:2},groups:{construction:{asked:120,waitRate:60},vehicles:{asked:200,waitRate:40},tactics:{asked:300,waitRate:12}},history:Array.from({length:120},(_,i)=>({at:now-5400000+i*30000,gameSeconds:i*27,credits:10000+Math.sin(i/9)*6000+i*110,freeCredits:6000+Math.sin(i/9)*4000+i*90,decisions:Math.floor(i*3.4),ownUnits:8+Math.floor(i/4),ownBuildings:6+Math.floor(i/20),enemyUnits:Math.max(0,Math.round(6+Math.sin(i/7)*5)),ownBuilt:Math.floor(i/3),ownLost:Math.floor(i/8),enemyDestroyed:Math.floor(i/2.5)}))};
 const matchB={...matchA,id:'b',startedAt:now-9000000,endedAt:now-7200000,durationMs:1800000,gameSeconds:1700,providerName:'Laya',provider:'local',providerKind:'local',model:'laya-multilingual-mlx',configuredModel:'laya',callMode:'',endpoint:'http://127.0.0.1:8742/v1/systemone',inputTokens:310000,outputTokens:0,totalTokens:310000,reason:'defeated_or_observer',outcome:'defeat',decisions:386,credits:{start:10000,end:1200,max:12000,min:300},armyMax:12,produced:{HTNK:6}};
 matchA.meta={pageTitle:'王二火大 · 盟军战役 第3关',url:'https://ra2web.github.io/#campaign/allied/3',me:{name:'Player',country:'America'},players:[{name:'Player',country:'America',allied:true,isAi:false,combatant:true},{name:'Soviet AI',country:'Russia',allied:false,isAi:true,combatant:true}],playerCount:2,opponents:1,map:{width:120,height:120},startTick:1619,startTime:107};matchA.label=matchA.label??'';matchA.notes=matchA.notes??'';matchA.ledger={ownUnitsLost:9,ownBuildingsLost:1,enemyUnitsDestroyed:41,enemyBuildingsDestroyed:12};
 const logA=[{at:now-5400000,kind:'session',event:'start',provider:'jev',model:'jev-latest'},{at:now-5399000,kind:'meta',tick:1619,pageTitle:matchA.meta.pageTitle,playerCount:2},...Array.from({length:60},(_,i)=>({at:now-5390000+i*60000,kind:'decision',tick:1700+i*60,provider:'openai',model:'gpt-4.1-2025-04-14',latencyMs:1600+Math.round(Math.sin(i)*500),inputTokens:2200,outputTokens:100,groups:{construction:{choice:i%3?'wait':'produce_GAPOWR',confidence:.6,...(i%7?{}:{fallback:true})},tactics:{choice:i%2?'engage_visible':'assault_1003',confidence:.9,reason:i%2?'Enemies are in range; keep firing.':'The barracks is exposed; take it out.'}}})),{at:now-3000000,kind:'action',tick:4000,question:'scouting',choice:'explore_80_90',auto:true,accepted:true,reason:'auto_explore'},{at:now-1800000,kind:'outcome',tick:9000,result:'victory'},{at:now-1800000,kind:'stop',tick:9000,reason:'victory'}];
 if(m.type==='MATCHES_LIST')return {ok:true,value:{matches:[matchA,matchB].map(({history,...x})=>({...x,samples:history.length}))}};
 if(m.type==='MATCH_LOG_GET')return {ok:true,value:{id:m.id,entries:m.id==='a'?logA:[]}};
 if(m.type==='MATCH_UPDATE'){const t=m.id==='b'?matchB:matchA;if(typeof m.label==='string')t.label=m.label;if(typeof m.notes==='string')t.notes=m.notes;if(['victory','defeat',''].includes(m.outcome)){t.outcome=m.outcome;t.outcomeMarked=!!m.outcome;}return {ok:true,value:t};}
 if(m.type==='MATCH_DELETE')return {ok:true,value:{deleted:m.id}};
 if(m.type==='MATCH_GET')return {ok:true,value:m.id==='b'?matchB:matchA};
 if(m.type==='MATCHES_CLEAR')return {ok:true,value:{matches:0}};
 if(m.type==='MATCH_SET_OUTCOME'){const t=m.id==='b'?matchB:matchA;t.outcome=m.outcome;t.outcomeMarked=!!m.outcome;return {ok:true,value:t};}
 if(m.type==='GET_STATUS'){if(status.observation)status.observation.at=Date.now();return {ok:true,value:status};}
 if(m.type==='SAVE_SETTINGS'){const {apiKey,localKey,openaiKey,...rest}=m.settings;settings={...rest,apiKey,localKey,openaiKey,hasKey:!!apiKey,hasLocalKey:!!localKey,hasOpenaiKey:!!openaiKey,providerName:NAMES[rest.provider]};localStorage.previewProvider=rest.provider;status.providerName=settings.providerName;return {ok:true,value:{...settings,permitted:granted,origin:ORIGINS[settings.provider]}};}
 if(m.type==='CLEAR_KEY'){if(m.provider==='openai'){settings.hasOpenaiKey=false;settings.openaiKey='';}else if(m.provider==='local'){settings.hasLocalKey=false;settings.localKey='';}else{settings.hasKey=false;settings.apiKey='';}status.running=false;return {ok:true,value:{}};}
 if(m.type==='START'){status.running=true;return {ok:true,value:status};}
 if(m.type==='STOP'){status.running=false;status.reason='manual';return {ok:true,value:status};}
 return {ok:false,error:'Unknown preview operation'};
}}};`;
const allowed=new Set(['popup.html','popup.css','popup.js','help.html','help.css','help.js','content.js','dashboard.html','dashboard.css','dashboard.js']);
http.createServer(async(req,res)=>{
 const name=new URL(req.url,'http://localhost').pathname.slice(1)||'popup.html';
 if(name==='preview-mock.js'){res.setHeader('Content-Type','text/javascript');res.end(mock);return;}
 if(!allowed.has(name)){res.writeHead(404);res.end();return;}
 try{let body=await fs.readFile(new URL('../dist/'+name,import.meta.url));if(name==='dashboard.html')body=body.toString().replace('<script type="module"','<script src="preview-mock.js"></script><script type="module"');
 if(name==='popup.html'){body=body.toString().replace('<script type="module"','<script src="preview-mock.js"></script><script type="module"');if(new URL(req.url,'http://localhost').searchParams.has('overlay'))body=body.replace('</body>','<script src="content.js"></script></body>');}res.setHeader('Content-Type',name.endsWith('.html')?'text/html; charset=utf-8':name.endsWith('.css')?'text/css':'text/javascript');res.setHeader('Cache-Control','no-store');res.end(body);}catch{res.writeHead(404);res.end();}
}).listen(4318,'127.0.0.1',()=>console.log('UI fixtures only: http://127.0.0.1:4318/ (populated), /?empty (lobby). No model or game connection.'));
